[Interface]
PrivateKey = <wg private key>
Address = 10.0.0.2/24
DNS = 1.1.1.1, 8.8.8.8
MTU = 1280

[Peer]
PublicKey = <wg public key>
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1
Endpoint = 127.0.0.1:51820
PersistentKeepalive = 25